# Colors
coquelicot="#FF8080"
zinnia="#FFBA9D"
bruyere="#8ABE8A"
anemone="#485571"
bleuet="#6D89A7"
lis="#C9D9D8"

lulumi="#A8DFDC"
maomi="#323333"

black="#101010"
gray1="#141414"
gray2="#181818"
gray3="#2A2A2A"
gray4="#3D3D3D"
gray5="#525252"
gray6="#676767"
gray7="#939393"
gray8="#B7B7B7"
gray9="#EDEDED"

# General Settings
set -g default-terminal "${TERM}"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'
setw -g xterm-keys on
set -g base-index 1
setw -g pane-base-index 1
set -g mouse on
set -g status-interval 1

# Styles & UI
set -g mode-style "bg=$gray8,fg=$gray1"
set -g message-style "fg=$gray6"
set -g message-command-style "bg=$gray6,fg=$gray4"

set -g pane-border-lines "heavy"
set -g pane-border-style "fg=$gray3"
set -g pane-active-border-style "fg=$lis"
set -g popup-border-lines "rounded"

set -g menu-style "fg=$lis,bg=$gray1"
set -g menu-selected-style "fg=$gray1,bg=$lis"
set -g copy-mode-match-style "fg=$gray1,bg=$gray8"
set -g copy-mode-current-match-style "fg=$gray1,bg=$gray8"

# Status Bar
set -g status-position bottom
set -g status-justify left
set -g status-style "bg=default"
set -g status-left-length 20
set -g status-right-length 20

set -g status-left "#[fg=${lis},bold] MAIN  "
set -g status-right "#[fg=${gray4}]%H:%M %m.%d.%y"

setw -g window-status-format "#[fg=${gray5}]#W "
setw -g window-status-current-format "#[fg=${gray8}]#W "
