coquelicot="#FF8080"
zinnia="#FFBA9D"
bruyere="#8ABE8A"
anemone="#485571"
bleuet="#6D89A7"
lis="#C9D9D8"

lulumi="#A8DFDC"
maomi="#323333"

black="#101010"
gray1="#141414"
gray2="#181818"
gray3="#2A2A2A"
gray4="#3D3D3D"
gray5="#525252"
gray6="#676767"
gray7="#939393"
gray8="#B7B7B7"
gray9="#EDEDED"

set -g default-terminal "xterm-256color"
setw -g xterm-keys on
set -g base-index 1
setw -g pane-base-index 1
set -g mouse on
set -g status-interval 1

set -g status-position bottom
set -g status-justify left
set -g status-style "bg=default"
set -g status-left-length 20
set -g status-right-length 0

set -g status-left "#[fg=${gray8},bold] MAIN  "
setw -g window-status-format "#[fg=${gray4}]#W "
setw -g window-status-current-format "#[fg=${gray6}]#W "
set -g pane-border-style "fg=${gray3}"
set -g pane-active-border-style "fg=${lis}"
set -g message-style "fg=${gray6}"
set -g status-right "#[fg=${gray4}]%H:%M %m.%d.%y"
