## Name: Fleur Dark

# Special
foreground = #B7B7B7
cursor = #EDEDED
background = #101010

# Black
color0 = #101010
color8 = #939393

# Red
color1 = #FF8080
color9 = #FFBA9D
color17 = #FF8080

# Green
color2 = #8ABE8A
color10 = #8ABE8A

# Yellow
color3 = #C9D9D8
color11 = #6D89A7

# Blue
color4 = #485571
color12 = #485571

# Purple
color5 = #6D89A7
color13 = #6D89A7

# Cyan
color6 = #A8DFDC
color14 = #A8DFDC

# White
color7 = #B7B7B7
color15 = #EDEDED

# Orange
color16 = #FFBA9D
